/**
 * RF-06c: elenco standard dei paesi per il campo `paese_residenza`
 * (§7.3) — codici ISO 3166-1 alpha-2. L'utente sceglie da un dropdown,
 * il valore salvato/inviato al backend resta sempre il codice a 2
 * lettere; l'etichetta mostrata si traduce in base alla lingua
 * dell'interfaccia (RNF-03), mai il dato memorizzato.
 *
 * Elenco degli stati membri/osservatori riconosciuti dalle Nazioni
 * Unite (standard per un selettore di residenza) — non l'elenco ISO
 * completo con ogni territorio/dipendenza, per restare maneggevole in
 * un dropdown senza perdere copertura reale.
 */
export interface Country {
  code: string;
  nameIt: string;
  nameEn: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", nameIt: "Afghanistan", nameEn: "Afghanistan" },
  { code: "AL", nameIt: "Albania", nameEn: "Albania" },
  { code: "DZ", nameIt: "Algeria", nameEn: "Algeria" },
  { code: "AD", nameIt: "Andorra", nameEn: "Andorra" },
  { code: "AO", nameIt: "Angola", nameEn: "Angola" },
  { code: "AG", nameIt: "Antigua e Barbuda", nameEn: "Antigua and Barbuda" },
  { code: "AR", nameIt: "Argentina", nameEn: "Argentina" },
  { code: "AM", nameIt: "Armenia", nameEn: "Armenia" },
  { code: "AU", nameIt: "Australia", nameEn: "Australia" },
  { code: "AT", nameIt: "Austria", nameEn: "Austria" },
  { code: "AZ", nameIt: "Azerbaigian", nameEn: "Azerbaijan" },
  { code: "BS", nameIt: "Bahamas", nameEn: "Bahamas" },
  { code: "BH", nameIt: "Bahrein", nameEn: "Bahrain" },
  { code: "BD", nameIt: "Bangladesh", nameEn: "Bangladesh" },
  { code: "BB", nameIt: "Barbados", nameEn: "Barbados" },
  { code: "BY", nameIt: "Bielorussia", nameEn: "Belarus" },
  { code: "BE", nameIt: "Belgio", nameEn: "Belgium" },
  { code: "BZ", nameIt: "Belize", nameEn: "Belize" },
  { code: "BJ", nameIt: "Benin", nameEn: "Benin" },
  { code: "BT", nameIt: "Bhutan", nameEn: "Bhutan" },
  { code: "BO", nameIt: "Bolivia", nameEn: "Bolivia" },
  { code: "BA", nameIt: "Bosnia ed Erzegovina", nameEn: "Bosnia and Herzegovina" },
  { code: "BW", nameIt: "Botswana", nameEn: "Botswana" },
  { code: "BR", nameIt: "Brasile", nameEn: "Brazil" },
  { code: "BN", nameIt: "Brunei", nameEn: "Brunei" },
  { code: "BG", nameIt: "Bulgaria", nameEn: "Bulgaria" },
  { code: "BF", nameIt: "Burkina Faso", nameEn: "Burkina Faso" },
  { code: "BI", nameIt: "Burundi", nameEn: "Burundi" },
  { code: "KH", nameIt: "Cambogia", nameEn: "Cambodia" },
  { code: "CM", nameIt: "Camerun", nameEn: "Cameroon" },
  { code: "CA", nameIt: "Canada", nameEn: "Canada" },
  { code: "CV", nameIt: "Capo Verde", nameEn: "Cabo Verde" },
  { code: "TD", nameIt: "Ciad", nameEn: "Chad" },
  { code: "CL", nameIt: "Cile", nameEn: "Chile" },
  { code: "CN", nameIt: "Cina", nameEn: "China" },
  { code: "CY", nameIt: "Cipro", nameEn: "Cyprus" },
  { code: "VA", nameIt: "Città del Vaticano", nameEn: "Vatican City" },
  { code: "CO", nameIt: "Colombia", nameEn: "Colombia" },
  { code: "KM", nameIt: "Comore", nameEn: "Comoros" },
  { code: "KP", nameIt: "Corea del Nord", nameEn: "North Korea" },
  { code: "KR", nameIt: "Corea del Sud", nameEn: "South Korea" },
  { code: "CI", nameIt: "Costa d'Avorio", nameEn: "Côte d'Ivoire" },
  { code: "CR", nameIt: "Costa Rica", nameEn: "Costa Rica" },
  { code: "HR", nameIt: "Croazia", nameEn: "Croatia" },
  { code: "CU", nameIt: "Cuba", nameEn: "Cuba" },
  { code: "DK", nameIt: "Danimarca", nameEn: "Denmark" },
  { code: "DM", nameIt: "Dominica", nameEn: "Dominica" },
  { code: "EC", nameIt: "Ecuador", nameEn: "Ecuador" },
  { code: "EG", nameIt: "Egitto", nameEn: "Egypt" },
  { code: "SV", nameIt: "El Salvador", nameEn: "El Salvador" },
  { code: "AE", nameIt: "Emirati Arabi Uniti", nameEn: "United Arab Emirates" },
  { code: "ER", nameIt: "Eritrea", nameEn: "Eritrea" },
  { code: "EE", nameIt: "Estonia", nameEn: "Estonia" },
  { code: "SZ", nameIt: "Eswatini", nameEn: "Eswatini" },
  { code: "ET", nameIt: "Etiopia", nameEn: "Ethiopia" },
  { code: "FJ", nameIt: "Figi", nameEn: "Fiji" },
  { code: "PH", nameIt: "Filippine", nameEn: "Philippines" },
  { code: "FI", nameIt: "Finlandia", nameEn: "Finland" },
  { code: "FR", nameIt: "Francia", nameEn: "France" },
  { code: "GA", nameIt: "Gabon", nameEn: "Gabon" },
  { code: "GM", nameIt: "Gambia", nameEn: "Gambia" },
  { code: "GE", nameIt: "Georgia", nameEn: "Georgia" },
  { code: "DE", nameIt: "Germania", nameEn: "Germany" },
  { code: "GH", nameIt: "Ghana", nameEn: "Ghana" },
  { code: "JM", nameIt: "Giamaica", nameEn: "Jamaica" },
  { code: "JP", nameIt: "Giappone", nameEn: "Japan" },
  { code: "GI", nameIt: "Gibilterra", nameEn: "Gibraltar" },
  { code: "DJ", nameIt: "Gibuti", nameEn: "Djibouti" },
  { code: "JO", nameIt: "Giordania", nameEn: "Jordan" },
  { code: "GR", nameIt: "Grecia", nameEn: "Greece" },
  { code: "GD", nameIt: "Grenada", nameEn: "Grenada" },
  { code: "GT", nameIt: "Guatemala", nameEn: "Guatemala" },
  { code: "GN", nameIt: "Guinea", nameEn: "Guinea" },
  { code: "GW", nameIt: "Guinea-Bissau", nameEn: "Guinea-Bissau" },
  { code: "GQ", nameIt: "Guinea Equatoriale", nameEn: "Equatorial Guinea" },
  { code: "GY", nameIt: "Guyana", nameEn: "Guyana" },
  { code: "HT", nameIt: "Haiti", nameEn: "Haiti" },
  { code: "HN", nameIt: "Honduras", nameEn: "Honduras" },
  { code: "HK", nameIt: "Hong Kong", nameEn: "Hong Kong" },
  { code: "IN", nameIt: "India", nameEn: "India" },
  { code: "ID", nameIt: "Indonesia", nameEn: "Indonesia" },
  { code: "IR", nameIt: "Iran", nameEn: "Iran" },
  { code: "IQ", nameIt: "Iraq", nameEn: "Iraq" },
  { code: "IE", nameIt: "Irlanda", nameEn: "Ireland" },
  { code: "IS", nameIt: "Islanda", nameEn: "Iceland" },
  { code: "IL", nameIt: "Israele", nameEn: "Israel" },
  { code: "IT", nameIt: "Italia", nameEn: "Italy" },
  { code: "KZ", nameIt: "Kazakistan", nameEn: "Kazakhstan" },
  { code: "KE", nameIt: "Kenya", nameEn: "Kenya" },
  { code: "KG", nameIt: "Kirghizistan", nameEn: "Kyrgyzstan" },
  { code: "KI", nameIt: "Kiribati", nameEn: "Kiribati" },
  { code: "KW", nameIt: "Kuwait", nameEn: "Kuwait" },
  { code: "LA", nameIt: "Laos", nameEn: "Laos" },
  { code: "LS", nameIt: "Lesotho", nameEn: "Lesotho" },
  { code: "LV", nameIt: "Lettonia", nameEn: "Latvia" },
  { code: "LB", nameIt: "Libano", nameEn: "Lebanon" },
  { code: "LR", nameIt: "Liberia", nameEn: "Liberia" },
  { code: "LY", nameIt: "Libia", nameEn: "Libya" },
  { code: "LI", nameIt: "Liechtenstein", nameEn: "Liechtenstein" },
  { code: "LT", nameIt: "Lituania", nameEn: "Lithuania" },
  { code: "LU", nameIt: "Lussemburgo", nameEn: "Luxembourg" },
  { code: "MO", nameIt: "Macao", nameEn: "Macao" },
  { code: "MG", nameIt: "Madagascar", nameEn: "Madagascar" },
  { code: "MW", nameIt: "Malawi", nameEn: "Malawi" },
  { code: "MV", nameIt: "Maldive", nameEn: "Maldives" },
  { code: "MY", nameIt: "Malesia", nameEn: "Malaysia" },
  { code: "ML", nameIt: "Mali", nameEn: "Mali" },
  { code: "MT", nameIt: "Malta", nameEn: "Malta" },
  { code: "MA", nameIt: "Marocco", nameEn: "Morocco" },
  { code: "MH", nameIt: "Marshall", nameEn: "Marshall Islands" },
  { code: "MR", nameIt: "Mauritania", nameEn: "Mauritania" },
  { code: "MU", nameIt: "Mauritius", nameEn: "Mauritius" },
  { code: "MX", nameIt: "Messico", nameEn: "Mexico" },
  { code: "MD", nameIt: "Moldavia", nameEn: "Moldova" },
  { code: "MC", nameIt: "Monaco", nameEn: "Monaco" },
  { code: "MN", nameIt: "Mongolia", nameEn: "Mongolia" },
  { code: "ME", nameIt: "Montenegro", nameEn: "Montenegro" },
  { code: "MZ", nameIt: "Mozambico", nameEn: "Mozambique" },
  { code: "MM", nameIt: "Myanmar", nameEn: "Myanmar" },
  { code: "NA", nameIt: "Namibia", nameEn: "Namibia" },
  { code: "NR", nameIt: "Nauru", nameEn: "Nauru" },
  { code: "NP", nameIt: "Nepal", nameEn: "Nepal" },
  { code: "NI", nameIt: "Nicaragua", nameEn: "Nicaragua" },
  { code: "NE", nameIt: "Niger", nameEn: "Niger" },
  { code: "NG", nameIt: "Nigeria", nameEn: "Nigeria" },
  { code: "NO", nameIt: "Norvegia", nameEn: "Norway" },
  { code: "NZ", nameIt: "Nuova Zelanda", nameEn: "New Zealand" },
  { code: "OM", nameIt: "Oman", nameEn: "Oman" },
  { code: "NL", nameIt: "Paesi Bassi", nameEn: "Netherlands" },
  { code: "PK", nameIt: "Pakistan", nameEn: "Pakistan" },
  { code: "PW", nameIt: "Palau", nameEn: "Palau" },
  { code: "PS", nameIt: "Palestina", nameEn: "Palestine" },
  { code: "PA", nameIt: "Panama", nameEn: "Panama" },
  { code: "PG", nameIt: "Papua Nuova Guinea", nameEn: "Papua New Guinea" },
  { code: "PY", nameIt: "Paraguay", nameEn: "Paraguay" },
  { code: "PE", nameIt: "Perù", nameEn: "Peru" },
  { code: "PL", nameIt: "Polonia", nameEn: "Poland" },
  { code: "PT", nameIt: "Portogallo", nameEn: "Portugal" },
  { code: "QA", nameIt: "Qatar", nameEn: "Qatar" },
  { code: "GB", nameIt: "Regno Unito", nameEn: "United Kingdom" },
  { code: "CZ", nameIt: "Repubblica Ceca", nameEn: "Czechia" },
  { code: "CF", nameIt: "Repubblica Centrafricana", nameEn: "Central African Republic" },
  { code: "CD", nameIt: "Repubblica Democratica del Congo", nameEn: "DR Congo" },
  { code: "CG", nameIt: "Repubblica del Congo", nameEn: "Congo" },
  { code: "DO", nameIt: "Repubblica Dominicana", nameEn: "Dominican Republic" },
  { code: "RO", nameIt: "Romania", nameEn: "Romania" },
  { code: "RW", nameIt: "Ruanda", nameEn: "Rwanda" },
  { code: "RU", nameIt: "Russia", nameEn: "Russia" },
  { code: "EH", nameIt: "Sahara Occidentale", nameEn: "Western Sahara" },
  { code: "KN", nameIt: "Saint Kitts e Nevis", nameEn: "Saint Kitts and Nevis" },
  { code: "LC", nameIt: "Saint Lucia", nameEn: "Saint Lucia" },
  { code: "VC", nameIt: "Saint Vincent e Grenadine", nameEn: "Saint Vincent and the Grenadines" },
  { code: "WS", nameIt: "Samoa", nameEn: "Samoa" },
  { code: "SM", nameIt: "San Marino", nameEn: "San Marino" },
  { code: "ST", nameIt: "São Tomé e Príncipe", nameEn: "São Tomé and Príncipe" },
  { code: "SN", nameIt: "Senegal", nameEn: "Senegal" },
  { code: "RS", nameIt: "Serbia", nameEn: "Serbia" },
  { code: "SC", nameIt: "Seychelles", nameEn: "Seychelles" },
  { code: "SL", nameIt: "Sierra Leone", nameEn: "Sierra Leone" },
  { code: "SG", nameIt: "Singapore", nameEn: "Singapore" },
  { code: "SY", nameIt: "Siria", nameEn: "Syria" },
  { code: "SK", nameIt: "Slovacchia", nameEn: "Slovakia" },
  { code: "SI", nameIt: "Slovenia", nameEn: "Slovenia" },
  { code: "SO", nameIt: "Somalia", nameEn: "Somalia" },
  { code: "ES", nameIt: "Spagna", nameEn: "Spain" },
  { code: "LK", nameIt: "Sri Lanka", nameEn: "Sri Lanka" },
  { code: "US", nameIt: "Stati Uniti", nameEn: "United States" },
  { code: "ZA", nameIt: "Sudafrica", nameEn: "South Africa" },
  { code: "SD", nameIt: "Sudan", nameEn: "Sudan" },
  { code: "SS", nameIt: "Sudan del Sud", nameEn: "South Sudan" },
  { code: "SE", nameIt: "Svezia", nameEn: "Sweden" },
  { code: "CH", nameIt: "Svizzera", nameEn: "Switzerland" },
  { code: "SR", nameIt: "Suriname", nameEn: "Suriname" },
  { code: "TJ", nameIt: "Tagikistan", nameEn: "Tajikistan" },
  { code: "TW", nameIt: "Taiwan", nameEn: "Taiwan" },
  { code: "TZ", nameIt: "Tanzania", nameEn: "Tanzania" },
  { code: "TH", nameIt: "Thailandia", nameEn: "Thailand" },
  { code: "TL", nameIt: "Timor Est", nameEn: "Timor-Leste" },
  { code: "TG", nameIt: "Togo", nameEn: "Togo" },
  { code: "TO", nameIt: "Tonga", nameEn: "Tonga" },
  { code: "TT", nameIt: "Trinidad e Tobago", nameEn: "Trinidad and Tobago" },
  { code: "TN", nameIt: "Tunisia", nameEn: "Tunisia" },
  { code: "TR", nameIt: "Turchia", nameEn: "Turkey" },
  { code: "TM", nameIt: "Turkmenistan", nameEn: "Turkmenistan" },
  { code: "TV", nameIt: "Tuvalu", nameEn: "Tuvalu" },
  { code: "UA", nameIt: "Ucraina", nameEn: "Ukraine" },
  { code: "UG", nameIt: "Uganda", nameEn: "Uganda" },
  { code: "HU", nameIt: "Ungheria", nameEn: "Hungary" },
  { code: "UY", nameIt: "Uruguay", nameEn: "Uruguay" },
  { code: "UZ", nameIt: "Uzbekistan", nameEn: "Uzbekistan" },
  { code: "VU", nameIt: "Vanuatu", nameEn: "Vanuatu" },
  { code: "VE", nameIt: "Venezuela", nameEn: "Venezuela" },
  { code: "VN", nameIt: "Vietnam", nameEn: "Vietnam" },
  { code: "YE", nameIt: "Yemen", nameEn: "Yemen" },
  { code: "ZM", nameIt: "Zambia", nameEn: "Zambia" },
  { code: "ZW", nameIt: "Zimbabwe", nameEn: "Zimbabwe" },
];

export const COUNTRY_CODES = new Set(COUNTRIES.map((c) => c.code));
